<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Ingeniería de Caracterización (feature engineering) | Análisis Exploratorio de Datos: Valor de Viviendas en California</title>
  <meta name="description" content="Realizar un Análisis Exploratorio de Datos (EDA) sobre la base de datos housing.csv, con el fin de comprender el comportamiento de la variable median_house_value (valor medio de las viviendas), la cual constituye nuestra variable de estudio central, así como su relación con las demás variables predictoras disponibles." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Ingeniería de Caracterización (feature engineering) | Análisis Exploratorio de Datos: Valor de Viviendas en California" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Realizar un Análisis Exploratorio de Datos (EDA) sobre la base de datos housing.csv, con el fin de comprender el comportamiento de la variable median_house_value (valor medio de las viviendas), la cual constituye nuestra variable de estudio central, así como su relación con las demás variables predictoras disponibles." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Ingeniería de Caracterización (feature engineering) | Análisis Exploratorio de Datos: Valor de Viviendas en California" />
  
  <meta name="twitter:description" content="Realizar un Análisis Exploratorio de Datos (EDA) sobre la base de datos housing.csv, con el fin de comprender el comportamiento de la variable median_house_value (valor medio de las viviendas), la cual constituye nuestra variable de estudio central, así como su relación con las demás variables predictoras disponibles." />
  

<meta name="author" content="Karla Paredes y Mauricio Orozco" />


<meta name="date" content="2026-08-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="variable-categórica-ocean_proximity-convertida-en-factor.html"/>
<link rel="next" href="conclusiones-generales.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> EDA</a>
<ul>
<li class="chapter" data-level="2.0.1" data-path="intro.html"><a href="intro.html#cargar-las-librerias"><i class="fa fa-check"></i><b>2.0.1</b> Cargar las librerias</a></li>
<li class="chapter" data-level="2.0.2" data-path="intro.html"><a href="intro.html#leer-dataset"><i class="fa fa-check"></i><b>2.0.2</b> Leer dataset</a></li>
<li class="chapter" data-level="2.0.3" data-path="intro.html"><a href="intro.html#mostrar-las-5-primeras-filas"><i class="fa fa-check"></i><b>2.0.3</b> Mostrar las 5 primeras filas</a></li>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#estructura-de-los-datos-variables-existentes-tipo-de-variable-etc"><i class="fa fa-check"></i><b>2.1</b> Estructura de los datos (Variables existentes, tipo de variable, etc…)</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="intro.html"><a href="intro.html#verificar-si-hay-datos-faltantes"><i class="fa fa-check"></i><b>2.1.1</b> Verificar si hay datos faltantes</a></li>
<li class="chapter" data-level="2.1.2" data-path="intro.html"><a href="intro.html#imputacion-de-datos-faltantes"><i class="fa fa-check"></i><b>2.1.2</b> Imputacion de datos faltantes</a></li>
<li class="chapter" data-level="2.1.3" data-path="intro.html"><a href="intro.html#ver-si-hay-datos-faltantes-nuevamente-pero-en-esta-ocasion-en-nuestro-data-frame"><i class="fa fa-check"></i><b>2.1.3</b> Ver si hay datos faltantes nuevamente, pero en esta ocasion, en nuestro Data Frame</a></li>
<li class="chapter" data-level="2.1.4" data-path="intro.html"><a href="intro.html#vamos-a-convertir-la-variable-cualitativa-ocean_proximity-en-un-factor"><i class="fa fa-check"></i><b>2.1.4</b> Vamos a convertir la variable cualitativa `ocean_proximity´ en un factor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="analisis-exploratorio-de-median_hose_value-target.html"><a href="analisis-exploratorio-de-median_hose_value-target.html"><i class="fa fa-check"></i><b>3</b> Analisis exploratorio de median_hose_value (target)</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="analisis-exploratorio-de-median_hose_value-target.html"><a href="analisis-exploratorio-de-median_hose_value-target.html#realicemos-el-resumen-estadistico-de-la-variable"><i class="fa fa-check"></i><b>3.0.1</b> Realicemos el resumen estadistico de la variable:</a></li>
<li class="chapter" data-level="3.0.2" data-path="analisis-exploratorio-de-median_hose_value-target.html"><a href="analisis-exploratorio-de-median_hose_value-target.html#gr%C3%A1fico-tipo-histograma-de-median_house_value"><i class="fa fa-check"></i><b>3.0.2</b> Gráfico tipo histograma de ‘median_house_value’</a></li>
<li class="chapter" data-level="3.1" data-path="analisis-exploratorio-de-median_hose_value-target.html"><a href="analisis-exploratorio-de-median_hose_value-target.html#gr%C3%A1fico-de-cajas-y-bigotes-de-median_house_value"><i class="fa fa-check"></i><b>3.1</b> Gráfico de cajas y bigotes de ‘median_house_value’</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="variables-independientes-caracteristicas.html"><a href="variables-independientes-caracteristicas.html"><i class="fa fa-check"></i><b>4</b> Variables independientes (caracteristicas)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="variables-independientes-caracteristicas.html"><a href="variables-independientes-caracteristicas.html#veamos-el-an%C3%A1lisis-de-cada-variable-independiente"><i class="fa fa-check"></i><b>4.1</b> Veamos el análisis de cada variable independiente</a></li>
<li class="chapter" data-level="4.2" data-path="variables-independientes-caracteristicas.html"><a href="variables-independientes-caracteristicas.html#graficos-de-las-variables-independientes"><i class="fa fa-check"></i><b>4.2</b> Graficos de las variables independientes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analisis-exploratorio-bivariado.html"><a href="analisis-exploratorio-bivariado.html"><i class="fa fa-check"></i><b>5</b> Analisis exploratorio bivariado</a>
<ul>
<li class="chapter" data-level="5.1" data-path="analisis-exploratorio-bivariado.html"><a href="analisis-exploratorio-bivariado.html#veamos-los-gr%C3%A1ficos."><i class="fa fa-check"></i><b>5.1</b> Veamos los gráficos.</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-categórica-ocean_proximity-convertida-en-factor.html"><a href="variable-categórica-ocean_proximity-convertida-en-factor.html"><i class="fa fa-check"></i><b>6</b> Variable categórica ‘ocean_proximity’ (convertida en factor)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-categórica-ocean_proximity-convertida-en-factor.html"><a href="variable-categórica-ocean_proximity-convertida-en-factor.html#ahora-comparemos-el-valor-medio-de-la-vivienda-seg%C3%BAn-la-proximidad-al-oceano"><i class="fa fa-check"></i><b>6.1</b> Ahora comparemos el valor medio de la vivienda según la proximidad al oceano</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-categórica-ocean_proximity-convertida-en-factor.html"><a href="variable-categórica-ocean_proximity-convertida-en-factor.html#grafico-de-cajas-y-bigotes-para-comparar-median_house_value-y-ocean_proximity"><i class="fa fa-check"></i><b>6.1.1</b> Grafico de cajas y bigotes para comparar ‘median_house_value’ y ‘ocean_proximity’</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-categórica-ocean_proximity-convertida-en-factor.html"><a href="variable-categórica-ocean_proximity-convertida-en-factor.html#paquete-ggally"><i class="fa fa-check"></i><b>6.2</b> Paquete GGally</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-categórica-ocean_proximity-convertida-en-factor.html"><a href="variable-categórica-ocean_proximity-convertida-en-factor.html#graficos-de-variables-independientes-vs-variables-independientes"><i class="fa fa-check"></i><b>6.2.1</b> Graficos de variables independientes vs variables independientes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ingeniería-de-caracterización-feature-engineering.html"><a href="ingeniería-de-caracterización-feature-engineering.html"><i class="fa fa-check"></i><b>7</b> Ingeniería de Caracterización (feature engineering)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ingeniería-de-caracterización-feature-engineering.html"><a href="ingeniería-de-caracterización-feature-engineering.html#graficos-de-variables-para-realizar-la-ingenieria-de-caracterizacion"><i class="fa fa-check"></i><b>7.1</b> Graficos de variables para realizar la “Ingenieria de caracterizacion”</a></li>
<li class="chapter" data-level="7.2" data-path="ingeniería-de-caracterización-feature-engineering.html"><a href="ingeniería-de-caracterización-feature-engineering.html#realizamos-el-procedimiento-de-ingenieria-de-caracterizacion"><i class="fa fa-check"></i><b>7.2</b> Realizamos el procedimiento de ingenieria de caracterizacion</a></li>
<li class="chapter" data-level="7.3" data-path="ingeniería-de-caracterización-feature-engineering.html"><a href="ingeniería-de-caracterización-feature-engineering.html#verificar-el-%C3%A9xito-de-la-ingenieria-de-caracterizacion"><i class="fa fa-check"></i><b>7.3</b> Verificar el éxito de la ingenieria de caracterizacion</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ingeniería-de-caracterización-feature-engineering.html"><a href="ingeniería-de-caracterización-feature-engineering.html#diagramas-de-dispersi%C3%B3n-de-las-nuevas-variables-vs-median_house_value"><i class="fa fa-check"></i><b>7.3.1</b> Diagramas de dispersión de las nuevas variables vs ‘median_house_value’</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="conclusiones-generales.html"><a href="conclusiones-generales.html"><i class="fa fa-check"></i><b>8</b> Conclusiones generales</a></li>
<li class="chapter" data-level="9" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>9</b> Literature</a></li>
<li class="chapter" data-level="10" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>10</b> Methods</a>
<ul>
<li class="chapter" data-level="10.1" data-path="methods.html"><a href="methods.html#math-example"><i class="fa fa-check"></i><b>10.1</b> math example</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>11</b> Applications</a>
<ul>
<li class="chapter" data-level="11.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>11.1</b> Example one</a></li>
<li class="chapter" data-level="11.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>11.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>12</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis Exploratorio de Datos: Valor de Viviendas en California</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ingeniería-de-caracterización-feature-engineering" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Ingeniería de Caracterización (feature engineering)<a href="ingeniería-de-caracterización-feature-engineering.html#ingenier%C3%ADa-de-caracterizaci%C3%B3n-feature-engineering" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>La ingeniería de características (feature engineering) es el proceso de
crear nuevas variables a partir de las que ya tenemos, con el fin de que
representen mejor la información del dataset. Esto es útil porque, como se
vio en la sección anterior, varias variables (total_rooms, total_bedrooms,
population y households) se mueven de forma muy parecida entre sí, ya que
en el fondo todas miden el tamaño del bloque censal desde distintos
ángulos. Usarlas tal cual en un modelo puede generar redundancia, así que
en este caso la vamos a utilizar para crear variables de razón (ratios)
que combinen esta información y que aporten un dato más claro, como por
ejemplo cuántas habitaciones tiene un hogar en promedio, en lugar de
manejar los totales por separado.</p>
<div id="graficos-de-variables-para-realizar-la-ingenieria-de-caracterizacion" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Graficos de variables para realizar la “Ingenieria de caracterizacion”<a href="ingeniería-de-caracterización-feature-engineering.html#graficos-de-variables-para-realizar-la-ingenieria-de-caracterizacion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Elegimos estas gráficas guiándonos por lo que se observó en las 28 gráficas
de la sección anterior, donde se comparó cada variable independiente contra
las demás. De ahí seleccionamos las relaciones que mostraban el patrón más
marcado entre sí (total_bedrooms, total_rooms, households y population), ya
que son las que presentan mayor riesgo de estar midiendo lo mismo. También
incluimos longitude vs latitude, aunque no tiene que ver con el tamaño del
bloque, porque nos ayuda a entender la ubicación geográfica de los datos.
Esto nos sirve como base para justificar por qué vamos a crear variables
nuevas en lugar de usar los totales originales. Es posible que falten
algunas combinaciones por revisar más adelante.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-1" tabindex="-1"></a><span class="co"># ---&#39;total_bedrooms&#39; vs &#39;households&#39;---</span></span>
<span id="cb40-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-2" tabindex="-1"></a></span>
<span id="cb40-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-3" tabindex="-1"></a>g1<span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total_bedrooms, <span class="at">y =</span> households)) <span class="sc">+</span></span>
<span id="cb40-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&#39;purple&#39;</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Total de dormitorios&#39;</span>,</span>
<span id="cb40-8"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Unidades Familiares/domesticas&#39;</span>,</span>
<span id="cb40-9"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-9" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;&#39;total_bedrooms&#39; vs &#39;households&#39;&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-10"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-11"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-11" tabindex="-1"></a></span>
<span id="cb40-12"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-12" tabindex="-1"></a></span>
<span id="cb40-13"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-13" tabindex="-1"></a><span class="co"># ---&#39;total_rooms&#39; vs &#39;total_bedrooms&#39;---</span></span>
<span id="cb40-14"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-14" tabindex="-1"></a></span>
<span id="cb40-15"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-15" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-16"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span>total_rooms , <span class="at">y =</span> total_bedrooms )) <span class="sc">+</span></span>
<span id="cb40-17"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-17" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&#39;darkblue&#39;</span>) <span class="sc">+</span></span>
<span id="cb40-18"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-18" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-19"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-19" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Total de habitaciones&#39;</span>,</span>
<span id="cb40-20"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-20" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Total de dormitorios&#39;</span>,</span>
<span id="cb40-21"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-21" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot; &#39;total_rooms&#39; vs &#39;total_bedrooms&#39; &quot;</span>) <span class="sc">+</span></span>
<span id="cb40-22"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-22" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-23"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-23" tabindex="-1"></a></span>
<span id="cb40-24"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-24" tabindex="-1"></a></span>
<span id="cb40-25"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-25" tabindex="-1"></a><span class="co"># ---&#39;households&#39; vs &#39;population&#39; ---</span></span>
<span id="cb40-26"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-26" tabindex="-1"></a></span>
<span id="cb40-27"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-27" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-28"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-28" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> households , <span class="at">y =</span> population )) <span class="sc">+</span></span>
<span id="cb40-29"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-29" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&#39;gold3&#39;</span>) <span class="sc">+</span></span>
<span id="cb40-30"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-30" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-31"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-31" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Unidades familiares/domésticas&#39;</span>,</span>
<span id="cb40-32"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-32" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Población total por bloque censado&#39;</span>,</span>
<span id="cb40-33"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-33" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;&#39;households&#39; vs &#39;totalbedrooms&#39; &quot;</span>) <span class="sc">+</span></span>
<span id="cb40-34"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-34" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-35"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-35" tabindex="-1"></a></span>
<span id="cb40-36"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-36" tabindex="-1"></a></span>
<span id="cb40-37"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-37" tabindex="-1"></a><span class="co"># ---&#39;total_rooms&#39; vs &#39;households&#39;---</span></span>
<span id="cb40-38"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-38" tabindex="-1"></a></span>
<span id="cb40-39"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-39" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-40"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-40" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total_rooms , <span class="at">y =</span> households )) <span class="sc">+</span></span>
<span id="cb40-41"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-41" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&#39;darkgreen&#39;</span>) <span class="sc">+</span></span>
<span id="cb40-42"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-42" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-43"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-43" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Cantidad de habitaciones&#39;</span>,</span>
<span id="cb40-44"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-44" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Unidades familiares&#39;</span>,</span>
<span id="cb40-45"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-45" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot; &#39;total_rooms&#39; vs &#39;households&#39; &quot;</span>) <span class="sc">+</span></span>
<span id="cb40-46"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-46" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-47"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-47" tabindex="-1"></a></span>
<span id="cb40-48"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-48" tabindex="-1"></a></span>
<span id="cb40-49"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-49" tabindex="-1"></a><span class="co"># ---&#39;total_bedrooms&#39; vs &#39;population&#39;---</span></span>
<span id="cb40-50"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-50" tabindex="-1"></a></span>
<span id="cb40-51"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-51" tabindex="-1"></a>g5 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-52"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-52" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span>total_bedrooms , <span class="at">y =</span> population)) <span class="sc">+</span></span>
<span id="cb40-53"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-53" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&#39;darkorange&#39;</span>) <span class="sc">+</span></span>
<span id="cb40-54"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-54" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-55"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-55" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Cantidad de dormitorios&#39;</span>,</span>
<span id="cb40-56"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-56" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Poblacion censada&#39;</span>,</span>
<span id="cb40-57"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-57" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot; &#39;total_bedrooms&#39; vs &#39;population&#39; &quot;</span>) <span class="sc">+</span></span>
<span id="cb40-58"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-58" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-59"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-59" tabindex="-1"></a></span>
<span id="cb40-60"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-60" tabindex="-1"></a><span class="co"># ---&#39;total_rooms&#39; vs &#39;population&#39;---</span></span>
<span id="cb40-61"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-61" tabindex="-1"></a></span>
<span id="cb40-62"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-62" tabindex="-1"></a>g6 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb40-63"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-63" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>total_rooms,<span class="at">y=</span>population))<span class="sc">+</span></span>
<span id="cb40-64"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-64" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">color=</span><span class="st">&#39;brown&#39;</span>)<span class="sc">+</span></span>
<span id="cb40-65"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-65" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb40-66"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-66" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Cantidad de habitaciones&#39;</span>,<span class="at">y=</span><span class="st">&#39;Poblacion censada&#39;</span>, <span class="at">tittle=</span><span class="st">&quot;&#39;total_rooms&#39; vs &#39;population&#39;&quot;</span>)<span class="sc">+</span></span>
<span id="cb40-67"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-67" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-68"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-68" tabindex="-1"></a></span>
<span id="cb40-69"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-69" tabindex="-1"></a></span>
<span id="cb40-70"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-70" tabindex="-1"></a><span class="co"># ---&#39;longitude&#39; vs &#39;latitude&#39;---</span></span>
<span id="cb40-71"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-71" tabindex="-1"></a></span>
<span id="cb40-72"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-72" tabindex="-1"></a>g7 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb40-73"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-73" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span>longitude , <span class="at">y =</span>latitude )) <span class="sc">+</span></span>
<span id="cb40-74"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-74" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&#39;magenta3&#39;</span>) <span class="sc">+</span></span>
<span id="cb40-75"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-75" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb40-76"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-76" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Longitud&#39;</span>,</span>
<span id="cb40-77"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-77" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Latitud&#39;</span>,</span>
<span id="cb40-78"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-78" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot; &#39;longitude&#39; vs &#39;latitude&#39; &quot;</span>) <span class="sc">+</span></span>
<span id="cb40-79"><a href="ingeniería-de-caracterización-feature-engineering.html#cb40-79" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/block%201-1.png" alt="" width="672" /></p>
<p>total_bedrooms vs households</p>
<p>De la grafica podemos observar que la cercania de los puntos pueden llegar a formar una linea recta. Sin embargo, también se debe recalcar el pequeño
conjunto de puntos apilados verticalmente entre los 500-750 dormitorios. Podemos decir que este diagrama de dispersión nos señala que la relación es notoriamente creciente.</p>
<p>total_rooms vs total_bedrooms</p>
<p>Acá también se aprecia una tendencia ascendente clara, aunque los puntos
ya no se ajustan tanto a la línea como en el caso anterior; se van
dispersando más a medida que aumentan los valores, formando algo así como
un abanico. De todas formas, la tendencia de fondo se mantiene: a más
habitaciones en total, más dormitorios, lo cual es coherente ya que los
dormitorios forman parte de esas habitaciones.</p>
<p><img src="bookdown-demo_files/figure-html/block%202-1.png" alt="" width="672" /></p>
<p>households vs population</p>
<p>La gráfica muestra una tendencia ascendente, aunque con más dispersión que
en g1, los puntos se van alejando de la línea conforme aumentan los
valores, y se distinguen un par de casos que se despegan bastante del
patrón general (bloques con una población muy alta en relación a su
cantidad de hogares, cerca de los 30,000-35,000). Aun con eso, se mantiene
la idea de que a más hogares corresponde mayor población.</p>
<p>total_rooms vs households</p>
<p>En este grafico la tendencia es ascendente, pero la dispersión aumenta hacia los valores más altos.
Esto va en línea con lo esperado, ya que un mayor número de hogares suele venir
acompañado de un mayor número de habitaciones en total, siguiendo el mismo
patrón de “tamaño del bloque” que se ha visto en las variables anteriores.</p>
<p><img src="bookdown-demo_files/figure-html/block%203-1.png" alt="" width="672" /></p>
<p>total_bedrooms vs population</p>
<p>Se observa una tendencia ascendente, con un comportamiento similar
al de g3 y g4 en cuanto a la dispersión creciente, además de algunos
valores atípicos aislados en la parte superior (bloques con una población
considerablemente alta respecto a su cantidad de dormitorios). En términos
generales, la tendencia sigue apuntando a que más dormitorios se asocian
con mayor población.</p>
<p>total_rooms vs population</p>
<p>Esta grafica muestra la dispersión aumentando de forma más notoria en los valores altos y un par de outliers
que se alejan bastante de la línea (puntos con población cercana a los
30,000-35,000). Esto confirma que esta variable también sigue el mismo
patrón de tamaño y densidad del bloque censal, aunque en este caso la
relación se ve algo menos ajustada que en g1.
<img src="bookdown-demo_files/figure-html/block%204-1.png" alt="" width="672" /></p>
<p>longitude vs latitude</p>
<p>Esta gráfica es diferente porque no habla del “tamaño” del bloque, sino de
dónde está ubicado. Se ve que a medida que la longitud aumenta, la latitud
baja, así que hay una relación inversa entre las dos. También se notan dos
zonas donde se juntan más puntos: una arriba a la izquierda y otra abajo a
la derecha, lo que muestra que los datos no están repartidos parejo, sino
que se concentran en un par de zonas.</p>
</div>
<div id="realizamos-el-procedimiento-de-ingenieria-de-caracterizacion" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Realizamos el procedimiento de ingenieria de caracterizacion<a href="ingeniería-de-caracterización-feature-engineering.html#realizamos-el-procedimiento-de-ingenieria-de-caracterizacion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-1" tabindex="-1"></a>df_nuevo <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb41-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-3" tabindex="-1"></a>    <span class="at">bedroom_ratio =</span> total_bedrooms <span class="sc">/</span> total_rooms,         <span class="co">#proporcion de dormitorios sobre la cantidad de habitaciones</span></span>
<span id="cb41-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-4" tabindex="-1"></a>    <span class="at">rooms_per_household =</span> total_rooms <span class="sc">/</span> households,       <span class="co">#habitaciones promedio por hogar (tamaño de vivienda)</span></span>
<span id="cb41-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-5" tabindex="-1"></a>    <span class="at">population_per_household =</span> population <span class="sc">/</span> households,   <span class="co">#promedio de personas por hogar</span></span>
<span id="cb41-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-6" tabindex="-1"></a>    <span class="at">population_per_room =</span> population <span class="sc">/</span> total_rooms,        <span class="co">#densidad de personas por habitación (hacinamiento)</span></span>
<span id="cb41-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-7" tabindex="-1"></a>    <span class="at">bedrooms_per_household =</span> total_bedrooms <span class="sc">/</span> households, <span class="co">#dormitorios promedio por hogar</span></span>
<span id="cb41-8"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-8" tabindex="-1"></a>    </span>
<span id="cb41-9"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-9" tabindex="-1"></a>    </span>
<span id="cb41-10"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-10" tabindex="-1"></a>    </span>
<span id="cb41-11"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-11" tabindex="-1"></a>  )</span>
<span id="cb41-12"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-12" tabindex="-1"></a></span>
<span id="cb41-13"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-13" tabindex="-1"></a><span class="co"># revisar que se crearon correctamente</span></span>
<span id="cb41-14"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-14" tabindex="-1"></a>df_nuevo <span class="sc">%&gt;%</span> </span>
<span id="cb41-15"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-15" tabindex="-1"></a>  <span class="fu">select</span>(rooms_per_household, bedrooms_per_household, bedroom_ratio, </span>
<span id="cb41-16"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-16" tabindex="-1"></a>         population_per_household, population_per_room) <span class="sc">%&gt;%</span> </span>
<span id="cb41-17"><a href="ingeniería-de-caracterización-feature-engineering.html#cb41-17" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##  rooms_per_household bedrooms_per_household bedroom_ratio     population_per_household
##  Min.   :  0.8462    Min.   : 0.1499        Min.   :0.04594   Min.   :   0.6923       
##  1st Qu.:  4.4407    1st Qu.: 1.0059        1st Qu.:0.17536   1st Qu.:   2.4297       
##  Median :  5.2291    Median : 1.0491        Median :0.20331   Median :   2.8181       
##  Mean   :  5.4290    Mean   : 1.1044        Mean   :0.21448   Mean   :   3.0707       
##  3rd Qu.:  6.0524    3rd Qu.: 1.1004        3rd Qu.:0.24026   3rd Qu.:   3.2823       
##  Max.   :141.9091    Max.   :34.0667        Max.   :3.49267   Max.   :1243.3333       
##  population_per_room
##  Min.   :  0.01811  
##  1st Qu.:  0.43552  
##  Median :  0.51601  
##  Mean   :  0.61958  
##  3rd Qu.:  0.65687  
##  Max.   :392.63158</code></pre>
</div>
<div id="verificar-el-éxito-de-la-ingenieria-de-caracterizacion" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Verificar el éxito de la ingenieria de caracterizacion<a href="ingeniería-de-caracterización-feature-engineering.html#verificar-el-%C3%A9xito-de-la-ingenieria-de-caracterizacion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Comparamos las nuevas variables con respecto a nuestra variable respuesta ‘median_house_value’</p>
<div id="diagramas-de-dispersión-de-las-nuevas-variables-vs-median_house_value" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Diagramas de dispersión de las nuevas variables vs ‘median_house_value’<a href="ingeniería-de-caracterización-feature-engineering.html#diagramas-de-dispersi%C3%B3n-de-las-nuevas-variables-vs-median_house_value" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-1" tabindex="-1"></a>p_1<span class="ot">&lt;-</span> df_nuevo <span class="sc">%&gt;%</span>   </span>
<span id="cb43-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>rooms_per_household,<span class="at">y=</span>median_house_value))<span class="sc">+</span></span>
<span id="cb43-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">color=</span><span class="st">&#39;springgreen4&#39;</span>)<span class="sc">+</span></span>
<span id="cb43-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb43-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Habitaciones promedio por hogar&#39;</span>,<span class="at">y=</span><span class="st">&#39;Valor medio de la vivienda&#39;</span>, <span class="at">tittle=</span><span class="st">&quot; &#39;&#39; vs &#39;median_house_value&#39; &quot;</span>)<span class="sc">+</span></span>
<span id="cb43-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb43-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb43-7" tabindex="-1"></a>p_1</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/p_1-1.png" alt="" width="672" /></p>
<p>Al revisar el resumen estadístico de <code>rooms_per_household</code> se confirma lo
que se veía en la gráfica, la mitad de los datos está entre 4.4 y 6
habitaciones promedio por hogar, y la media (5.43) y la mediana (5.23)
están bastante cerca, así que el comportamiento normal es bien estable. Sin
embargo, el máximo (141.9) está muy lejos de ese rango, lo que confirma que
hay outliers extremos, y probablemente son esos los que están inflando la
línea de tendencia en el gráfico de dispersión.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-1" tabindex="-1"></a>p_2<span class="ot">&lt;-</span> df_nuevo <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>bedrooms_per_household,<span class="at">y=</span>median_house_value))<span class="sc">+</span></span>
<span id="cb44-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">color=</span><span class="st">&#39;goldenrod2&#39;</span>)<span class="sc">+</span></span>
<span id="cb44-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb44-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Dormitorios promedio por hogar&#39;</span>,<span class="at">y=</span><span class="st">&#39;Valor medio de la vivienda&#39;</span>, <span class="at">tittle=</span><span class="st">&quot;&#39;bedrooms_per_household&#39; vs &#39;median_house_value&#39;&quot;</span>)<span class="sc">+</span></span>
<span id="cb44-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb44-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-7" tabindex="-1"></a></span>
<span id="cb44-8"><a href="ingeniería-de-caracterización-feature-engineering.html#cb44-8" tabindex="-1"></a>p_2</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/p_2-1.png" alt="" width="672" /></p>
<p>La mayoría de los puntos están entre 0 y 5 en el eje X, con una fila
pegada arriba cerca de 500,000 (el mismo tope visto antes). De ahí para
arriba casi no hay datos, solo unos pocos puntos sueltos hasta 30-34. La
línea roja baja de forma marcada y hacia el final llega a valores
negativos, lo cual no tiene sentido real para el precio de una vivienda,
así que esa parte de la línea la están empujando muy pocos puntos
extremos y no el comportamiento general de los datos.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-1" tabindex="-1"></a>p_3<span class="ot">&lt;-</span> df_nuevo <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>bedroom_ratio,<span class="at">y=</span>median_house_value))<span class="sc">+</span></span>
<span id="cb45-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">color=</span><span class="st">&#39;mediumorchid3&#39;</span>)<span class="sc">+</span></span>
<span id="cb45-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb45-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Proporción de dormitorios sobre habitaciones&#39;</span>,<span class="at">y=</span><span class="st">&#39;Valor medio de la vivienda&#39;</span>, <span class="at">tittle=</span><span class="st">&quot; &#39;bedroom_ratio&#39; vs &#39;median_house_value&#39; &quot;</span>)<span class="sc">+</span></span>
<span id="cb45-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb45-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb45-7" tabindex="-1"></a>p_3</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/p_3-1.png" alt="" width="672" /></p>
<p>En esta gráfica casi todo se concentra entre 0 y 0.5 en el eje X, y de ahí
en adelante los datos prácticamente desaparecen, quedando solo unos pocos
puntos aislados hasta 3.5. A diferencia de las anteriores, acá no hay una
fila de puntos pegada arriba en el tope de 500,000, sino que la nube se ve
más dispersa en distintos valores de vivienda. La línea roja cae de forma
pronunciada y termina en valores negativos, algo que no es posible en la
realidad, lo que confirma que en esa zona (proporción mayor a 1) hay tan
pocos datos que la línea deja de representar el comportamiento real de la
variable.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-1" tabindex="-1"></a>p_4<span class="ot">&lt;-</span>df_nuevo <span class="sc">%&gt;%</span> </span>
<span id="cb46-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>population_per_household,<span class="at">y=</span>median_house_value))<span class="sc">+</span></span>
<span id="cb46-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">color=</span><span class="st">&#39;darkblue&#39;</span>)<span class="sc">+</span></span>
<span id="cb46-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb46-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Promedio de habitantes por hogar&#39;</span>,<span class="at">y=</span><span class="st">&#39;Valor medio de la vivienda&#39;</span>, <span class="at">tittle=</span><span class="st">&quot; &#39;population_per_household&#39; vs &#39;median_house_value&#39; &quot;</span>)<span class="sc">+</span></span>
<span id="cb46-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb46-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb46-7" tabindex="-1"></a>p_4</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/p_4-1.png" alt="" width="672" /></p>
<p>Casi todos los puntos están pegados al 0 en el eje X, formando una franja
vertical densa, y solo hay unos cuantos puntos sueltos hasta 1200. La línea
roja baja de forma suave, pero como casi no hay datos fuera de esa franja,
no es muy confiable para el resto del rango. La banda gris se abre bastante
hacia la derecha, confirmando que ahí casi no hay información.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-1" tabindex="-1"></a>p_5<span class="ot">&lt;-</span> df_nuevo <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>population_per_room,<span class="at">y=</span>median_house_value))<span class="sc">+</span></span>
<span id="cb47-3"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">color=</span><span class="st">&#39;lightsalmon&#39;</span>)<span class="sc">+</span></span>
<span id="cb47-4"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb47-5"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Densidad de personas por habitación&#39;</span>,<span class="at">y=</span><span class="st">&#39;Valor medio de la vivienda&#39;</span>, <span class="at">tittle=</span><span class="st">&quot; &#39;population_per_room&#39; vs &#39;median_house_value&#39; &quot;</span>)<span class="sc">+</span></span>
<span id="cb47-6"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb47-7"><a href="ingeniería-de-caracterización-feature-engineering.html#cb47-7" tabindex="-1"></a>p_5</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/p_5-1.png" alt="" width="672" /></p>
<p>Los puntos están pegados al 0 en el eje X, con solo un par de casos
aislados que llegan hasta 400. La línea roja baja de forma pronunciada y
termina en valores negativos, algo que no es posible en la realidad. Igual
que en las anteriores, esto pasa porque hay muy pocos datos fuera de esa
franja inicial, así que la tendencia que muestra la línea no refleja bien
el comportamiento general de los datos.</p>
<p>[Conclusiones]</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="variable-categórica-ocean_proximity-convertida-en-factor.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusiones-generales.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
